ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS work_hours TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hospital_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hospital_address TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS specialty TEXT NOT NULL DEFAULT '';